### ISSUE TITLE
pretrained model 

### ISSUE THREAD

**Issue by luoww1992** [Moon0316/T2A#2]
can you share the model for testing?

and i want to train a new model myself, how to make the train dataset ?

What is included in the blendshape pkl ? 
i know there are audio_data, vertice......

**Comment by Moon0316** [comment]
Sorry for the late reply. We use an unpublic dataset in our experiments, and the copyright is not reserved by us. As our model will be put into commercial use later, we couldn't provide the model checkpoint. However, I've unploaded a demo dataset, from which you could know the dataset structure as well as the blendshape pkl format. Please refer to the data folder in this repo to get more details. And if you correctly configure the environment as the README file, you will run the train.sh and test.sh in this repo successfully.
