### ISSUE TITLE
sdtw loss error

### ISSUE THREAD

**Issue by shanzhajuan** [Moon0316/T2A#5]
您好，您的工作效果非常棒。
我在试着训练您提供的网络时，softdtw loss 总是会报如下错误：
numba.cuda.cudadrv.driver.CudaAPIError: [1] Call to cuLaunchKernel results in CUDA_ERROR_INVALID_VALUE
报错位置在：sdtw_cuda_loss.py文件的
compute_softdtw_cuda[B, threads_per_block](cuda.as_cuda_array(D.detach()),
                                                   gamma.item(), bandwidth.item(), N, M, n_passes,
                                                   cuda.as_cuda_array(R))
如果我的训练batch_size是1，在迭代35个batch后，会报这个错误
如果我的训练batchsize 是8，在迭代到第6个batch后，会报这个错误
通过Google后，我怀疑是softdtw loss需要的cuda线程太多，我的gpu无法支持。但是由于不太懂softdtw loss部分的代码，不知道该如何修改。我的gpu是nvidia geforce rtx 3080.  显存10g
![image](https://github.com/Moon0316/T2A/assets/38515702/e316b327-0f06-4155-a784-464d735c4552)

**Comment by shanzhajuan** [comment]
原因应该是输入的音频时长太长了，我们缩短了序列长度后，就没有这个错误了。

**Comment by Moon0316** [comment]
是的，如果使用cuda版soft_dtw loss，序列长度不能过长，您也可以选择用cpu版的soft_dtw loss

**Comment by shanzhajuan** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我已经收到了您的邮件，会尽快处理。
