### ISSUE TITLE
关于generate_hubert

### ISSUE THREAD

**Issue by Rookie-Kai** [Moon0316/T2A#6]
您好，非常感谢您的工作
但是我在运行生成hubert特征时，使用您提供的A1.wav数据，出现了下述问题

Traceback (most recent call last):
  File "utils/generate_hubert.py", line 76, in <module>
    handle_wav(args.input_dir, os.path.join(args.output_dir, model_short_alias))
  File "utils/generate_hubert.py", line 54, in handle_wav
    torch.save(logits[2], os.path.join(saved_to_path, wav_file_dir, wav_file.split(".")[0] +".pt"))
IndexError: tuple index out of range

该问题导致最后生成的A1.pt在运行test.sh时因维度不匹配出现异常
请问这里的logits[2]是否需要修改？
谢谢

**Comment by Moon0316** [comment]
您好，我们在fairseq的源码上做了微小的改动，您可以检查一下有没有做这张图里的最后两步
![image](https://github.com/Moon0316/T2A/assets/86870625/44dd14ab-7200-4191-9682-287fdead1c3b)

**Comment by Rookie-Kai** [comment]
抱歉，我没有更改hubert内容，谢谢您
