### ISSUE TITLE
dilate loss

### ISSUE THREAD

**Issue by JaggerZr** [Moon0316/T2A#8]
您好，我注意到您的code中有dilate loss，我尝试了https://github.com/marcdemers/batch-DILATE/tree/main中的dilate，但是效果不好，您这边能帮忙提供代码或者相关的链接呢。

**Comment by Moon0316** [comment]
您好，我们用的DTW loss的实现已经放在[repo](https://github.com/Moon0316/T2A/blob/main/sdtw_cuda_loss.py)里了，参考的是这个[repo](https://github.com/keonlee9420/Soft-DTW-Loss)

**Comment by JaggerZr** [comment]
dilate loss能帮忙提供一下吗，谢谢

**Comment by Moon0316** [comment]
您好，我们的论文中并不涉及dilate loss，因为我们的pred和label时间长度可能不一致，这种情况下无法使用dilate loss，代码中的dilate是没有删除干净旧代码残留的

**Comment by JaggerZr** [comment]
你们自己是不是重写了dilate loss啊，我非常感兴趣，如果您同意分享的话，能否发到我的邮箱里呢，谢谢370872355@qq.com

**Comment by JaggerZr** [comment]
> 您好，我们的论文中并不涉及dilate loss，因为我们的pred和label时间长度可能不一致，这种情况下无法使用dilate loss，代码中的dilate是没有删除干净旧代码残留的

我尝试只用dtw，发现Infer的结果同步性有很大的问题，我查阅到dilate loss可以解决这个问题，尝试了https://github.com/vincent-leguen/DILATE 中的dilate，发现不收敛，但是同步性会好一些，所以想咨询您您这边是否自己写了dilate，或者有更好的dilate代码可以参考。

**Comment by Moon0316** [comment]
我们参考的就是DILATE loss的官方repo：https://github.com/vincent-leguen/DILATE/tree/master
时间久远，代码没有备份了，但是当时应该没有改写

**Comment by JaggerZr** [comment]
谢谢，不知您当时运行时有没有遇见DILATE loss出现负数的情况。

**Comment by Moon0316** [comment]
没有的
