### ISSUE TITLE
How to train the model with 30/60fps blendshape label

### ISSUE THREAD

**Issue by yonzhao** [Moon0316/T2A#9]
当前我们的blendshape标签数据是30/60fps，而不是25fps,  所以真实标签和模型输出完全对不上。想适配你们模型进行训练， 我尝试修改预训练模型hubert label_rate=60HZ, 但好像预训练模型修改不了。博主有什么更好的适配策略呢？

**Comment by Moon0316** [comment]
HuBERT的输出是50Hz的，这是预训练模型决定的，我们改不了。可以试试把blendshape通过插值的方式改成25fps的

**Comment by yonzhao** [comment]
非常感谢你的回复！ 还有一个问题想请教一下。我尝试在你的工程上增加dilate loss, 我们模型输出是shape（bath，xxx,37), dilate 接收的是 shape (batch_size, N_output, 1)，你们之前是如何转换到dilate接收到shape呢？我是通过如下图红色标注框标注的方式，但训练速度极其的慢，效果很差。
<img width="796" alt="WeChat355ee8232e64b0636f9ffc1b8b8b738b" src="https://github.com/user-attachments/assets/0a9b0e6a-8730-4bb3-97be-c8b4e5dc1ce1">
